library(testthat)
library(vdiffr)
library(nybem)
library(ecorest)
library(raster)
library(dplyr)
library(tmap)
library(rgdal)
library(rlang)
library(sf)
library(sp)
library(purrr)
library(exactextractr)
library(oysteR)
library(ggplot2)

test_check("nybem")
